export { default as BlockAdvantage } from './BlockAdvantage/BlockAdvantage'
export { default as BlockVideo } from './BlockVideo/BlockVIdeo'
export { default as BlockComparison } from './BlockComparison/BlockComparison'
export { default as BlockLife } from './BlockLife/BlockLife'
export { default as BlockBlog } from './BlockBlog/BlockBlog'
